language: node_js
node_js:
  - "8"
dist: trusty
sudo: false

cache:
  directories:
    - node_modules

addons:
  chrome: stable

install:
  - npm install

script:
  - npm run test
  - npm run build

deploy:
  provider: firebase
  token:
    secure: "1/5Vhi4oD35BmEkV1Hhrf233rGfmpz5cjQ2nr8xlhrtkDvlrpEJJxcwc7Gw2sMcUgP"
